# server config
server:
  host: "localhost"
  port: 3000

# database config
db:
  type: "mongodb"
  mongoConfig:
            # full endpoint: address + port
    URL: "mongodb://localhost:27017"
    ProjectsColl: "Projects"
    SchemasColl: "Schemas"